spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/LearnSSMForMysql?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

#Spring集成MyBatis环境
mybatis:
  #加载MyBatis映射文件，以Mapper.xml结尾的文件
  mapper-locations: classpath:mapping/*Mapper.xml
  #实体类扫描包
  type-aliases-package: com.example.demo1.entity
  
